### ISSUE TITLE
[MainPage] 메인 페이지 기능 구현

### ISSUE THREAD

**Issue by gunom** [TEAM-TATTOUR/tattour-client#10]
## 💚 어떤 기능인가요?
드래그를 통한 가로 스크롤 기능 구현
## ✅ To Dos

- [ ] HotCustomSection에 기능 적용

**Comment by lydiacho** [comment]
ToDo에도 관련 내용 포함 안되어있는 것 같은데, `가로 스크롤 기능`은 별도의 이슈로 빼는건 어떨까요?
이슈 단위 = PR 단위 = 코드리뷰 단위인데, `가로스크롤 구현`과 `세로 스크롤에 따른 CTA 노출`은 명확하게 다른 기능이라고 생각해서요!
