### ISSUE TITLE
[MyTattooPage] 내 타투 페이지 UI 구현

### ISSUE THREAD

**Issue by gunom** [TEAM-TATTOUR/tattour-client#12]
## 💚 어떤 기능인가요?
내 타투 페이지 UI 구현. 기능 제외
## ✅ To Dos
- [ ] 내 타투 리스트 UI 구현
- [ ] 내가 찜한 타투 리스트 UI 구현
- [ ] 각 타투의 상세 페이지 구현

**Comment by lydiacho** [comment]
ToDo에 타투 리스트 외에 `각 타투의 상세 페이지 구현`도 명시해주면 좋을 것 같아요~

**Comment by lydiacho** [comment]
내가 찜한 타투 리스트가 LIKE 맞죠?? 그거는 구현하지 말아주세요 공통 컴포넌트라서 여긴 제가 맡겠습니다~

**Comment by Yeonseo-Jo** [comment]
상세 페이지 구현은 pr 단위 분리하는건 어떤가요 ?!
