### ISSUE TITLE
[RegisterPage] 사용자 이름과 전화번호 입력받는 페이지 퍼블리싱

### ISSUE THREAD

**Issue by Arooming** [TEAM-TATTOUR/tattour-client#13]
## 💚 어떤 기능인가요?

- 사용자의 실명과 전화번호를 입력받는 뷰를 구현합니다.

## ✅ To Dos

- [x] 사용자 실명 입력받는 뷰
- [x] 사용자 전화번호 입력받는 뷰
- [x] 전화번호 인증 컴포넌트

**Comment by gunom** [comment]
이거 이슈를 쪼갰어야하는데 안쪼갰네요. 이름 입력과 전화번호 입력은 별개 같아보여요. 리뷰가 힘드네요.
