### ISSUE TITLE
[OrderPage] 2. 환불정책 안내 컴포넌트 퍼블리싱

### ISSUE THREAD

**Issue by lydiacho** [TEAM-TATTOUR/tattour-client#40]
## 💚 어떤 기능인가요?
마지막 컴포넌트 퍼블리싱 

## ✅ To Dos

- [ ] 체크박스
- [ ] 텍스트
- [ ] 버튼 아이콘

**Comment by Yeonseo-Jo** [comment]
주소지 검색 API 연결은 한 번 분리하는거 어떤가요 ?!
