### ISSUE TITLE
[CustomOnBoardingPage] 커스텀 도안 타투 온보딩 페이지 UI 구현

### ISSUE THREAD

**Issue by urjimyu** [TEAM-TATTOUR/tattour-client#65]
## 💚 어떤 기능인가요?
- 캐러셀을 통해 커스텀 도안 제작 희망시 온보딩 페이지 UI 구현하기

## ✅ To Dos

- [ ] 캐러셀 이용해서 온보딩 이미지 넣어주기
- [ ] 헤더 적용하기
- [ ] 하단에 신청서 적용 버튼 구현

**Comment by Yeonseo-Jo** [comment]
온보딩은 안에 이미지/헤더만 바꿔주면 돼서 제가 가져가겠습니당!
