### ISSUE TITLE
[CustomReferencePage] 커스텀 타투 크기 선택 화면 기능 구현

### ISSUE THREAD

**Issue by urjimyu** [TEAM-TATTOUR/tattour-client#68]
## 💚 어떤 기능인가요?
- 커스텀 타투 크기 선택하면 색깔 바뀌게 하고 버튼 누르면 다음 화면으로 넘어가게 설정하기

## ✅ To Dos

- [ ] 원하는 크기 선택시 색깔 달라지게 구현
- [ ] 프로그레스바 구현하기
- [ ] 다음 버튼 누르면 다음 화면 뜨도록 구현

**Comment by Yeonseo-Jo** [comment]
요것도 커스텀 타투의 앞부분이라 제가 가져가겠습니당 !!
