### ISSUE TITLE
[CustomReferencePage] 커스텀 타투 타투 크기 선택 화면 서버 연결

### ISSUE THREAD

**Issue by urjimyu** [TEAM-TATTOUR/tattour-client#69]
## 💚 어떤 기능인가요?
- 선택한 타투 크기 선택 후 다음 클릭 시 put으로 서버 통신해주기
## ✅ To Dos

- [ ] 다음 버튼 클릭 시 put으로 서버 통신하기

**Comment by Yeonseo-Jo** [comment]
요거 recoil로 한 번에 통신하기로 해서 서버랑 상의 후 + 진행 상황 보구 커스텀 타투 담당 둘 중 한 명(연서 or 지민)이 API 연결 한 번에 하면 될것 같습니당!
