### ISSUE TITLE
[CustomReferencePage] 레퍼런스 첨부 뷰 구현하기

### ISSUE THREAD

**Issue by urjimyu** [TEAM-TATTOUR/tattour-client#70]
## 💚 어떤 기능인가요?
- 레퍼런스 첨부하기 뷰 UI 구현

## ✅ To Dos

- [x] UI 구현하기

**Comment by Yeonseo-Jo** [comment]
프로그래스 바는 common component로 사용할것 같습니당! 참고 참고
