### ISSUE TITLE
[MainPage] 메인 페이지 UI 구현

### ISSUE THREAD

**Issue by gunom** [TEAM-TATTOUR/tattour-client#9]
## 💚 어떤 기능인가요?
MainPage의 기본 UI 구현. 기능 제외
## ✅ To Dos
- [x] OnboardingBanner
- [x] HotCustomSection
- [x] ThemeSection
- [x] EventBanner

**Comment by lydiacho** [comment]
ToDo에 Event 배너도 들어가면 좋을 것 같아요! 
우리 뷰에서 공통으로 쓰이는 컴포넌트가 두개고, 둘다 가로 스크롤이라서 
`Hot Topic`을 모건이 한다면, `비슷한제품 추천해드려요`/`LIKE`를 제가 하면 될 것 같네용
